controller_list:
  - name: l_arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - l_arm_pitch
      - l_arm_roll
      - l_arm_yaw
      - l_forearm_pitch
      - l_forearm_yaw
      - l_hand_roll
      - l_hand_pitch
  - name: r_arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r_arm_pitch
      - r_arm_roll
      - r_arm_yaw
      - r_forearm_pitch
      - r_forearm_yaw
      - r_hand_roll
      - r_hand_pitch