controller_list:
  - name: fake_kuavo_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - l_arm_pitch
      - l_arm_roll
      - l_arm_yaw
      - l_forearm_pitch
      - l_forearm_yaw
      - l_hand_roll
      - l_hand_pitch
  - name: fake_kuavo_hand_group_controller
    type: $(arg fake_execution_type)
    joints:
      - l_font_finger
initial:  # Define initial robot poses per group
  - group: kuavo_arm_group
    pose: kuavo_arm_base_pose