controller_list:
  - name: kuavo_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - l_arm_pitch
      - l_arm_roll
      - l_arm_yaw
      - l_forearm_pitch
      - l_forearm_yaw
      - l_hand_roll
      - l_hand_pitch